largura = float(input("Digite a largura do terreno: "))
comprimento = float(input("Digite o comprimento do terreno: "))
valor_metro_quadrado = float(input("Digite o valor do metro quadrado: "))
b = largura
h = comprimento
area = b * h
preco_terreno = area * valor_metro_quadrado
print("Area do terreno =", area)
print("Preco do terreno =", preco_terreno)
